### ISSUE TITLE
Output marked entries to STDOUT upon exiting

### ISSUE THREAD

**Issue by GSI** [lecram/rover#14]
Nice tool.

Would be interesting to have some sort of way (e.g. command line switch) that has **rover** output any entries marked upon exit;

This would allow useful piping to other commands.

**Comment by lecram** [comment]
This is something I've considered before, but we can't pipe rover's output since it's used to render the terminal user interface.

One alternative would be to pass a file name to rover and use named pipes, but the usability would be cumbersome. For example:

```
$ mkfifo foo
$ tar -c -z -T foo -f foo.tgz &
$ rover --save-marks foo
```

I'm not sure that would be worth it. Any suggestions?

**Comment by GSI** [comment]
Ah sure! Hadn't thought that through.

Writing to a file would be good. **rover** could output the file written to upon exist.

This way, when using `mktemp`, we would still know where the contents are to be found:

    # rover --save-marks `mktemp`

    Marked items written to /tmp/tmp.ximQ9gmX0v

**Comment by lecram** [comment]
Why not just save the output of `mktemp` in a shell variable? You can't read Rover's output from another program anyway (for the reason stated above)...

A `--save-marks` option was added in 89341368594bed1a12722f7dd72d1921d3ee0c49. It appends marked entries to the given file at exit. If the file doesn't exist, it's created. Appending is useful specifically because Rover can't mark entries from different directories at the same time so, depending on what you want to do, you might need to run `rover --save-marks /tmp/marks` multiple times.

**Comment by GSI** [comment]
Though useful, I'd consider "appending" as unexpected behaviour in this case - simply because "any other" tool out there would just overwrite. Maybe `-a` would be good (as in `tee(1)`).

**Comment by lecram** [comment]
So you want to make the default behavior less useful and add another option just because users expect the less useful behavior? I expect users to read the manual. :)

**Comment by GSI** [comment]
Exactly. Principle of least astonishment;

... and because "useful" doesn't equal "default use case" :)

Anyway I respect your decision, **rover** being your app after all.
