### ISSUE TITLE
Feature request: file type association support

### ISSUE THREAD

**Issue by ScrumpyJack** [lecram/rover#18]
"File browsers usually allow the user to open a file with an appropriate program. Rover is still very limited on this area."

I love rover and how uninvasive it is. Would be very useful to be able to use some kind of file type/application mapping to open files with external programs, something along the lines of a .rovercap file?

.doc application/msword; antiword %s
.pdf application/pdf; pdftotext %s 
.sc application/sc; sc %s

etc

**Comment by lecram** [comment]
See #15.

Adding a configuration file would be my last option. They clutter the file system. They need an ad hoc parser. I like to be able to "install" rover just by copying the executable file.

I suggest that you write a simple shell script that opens any given file with the appropriate application. You may start with something like this:

```sh
#! /bin/sh

case "$1" in
  *.htm|*.html)
    fmt="elinks %s" ;;
  *.pdf|*.xps|*.cbz|*.epub)
    fmt="mutool draw -F txt %s | less" ;;
  *.ogg|*.flac|*.wav|*.mp3)
    fmt="play %s" ;;
  *.[1-9])
    fmt="man -l %s" ;;
  *.c|*.h|*.sh|*.lua|*.py|*.ml|*[Mm]akefile)
    fmt="vim %s" ;;
  *)
    fmt="less %s"
esac

exec sh -c "$(printf "$fmt" "\"$1\"")"
```

Save this file as "open" (or whatever), make it executable and put it somewhere in $PATH. Than you can use it with Rover:

```console
$ PAGER=open rover
```

This requires no change to Rover. The "configuration file" is completely optional. The "parser" is the shell interpreter itself, with powerful and standardized syntax & semantics. You can extend the functionality in many ways: using `file(1)` to match by MIME type, using xdg-open (or similar) to open applications on separated windows, etc. You can also use the same script with other file browsers!

One change that I *do* think might be worth is associating a Rover-specific environmental variable, say $ROVER_OPEN, to a new keybinding (say, `o`) so that we can keep using $PAGER (`SPACE`) in the traditional way:

```console
$ PAGER=less ROVER_OPEN=open rover
$ # pressing SPACE always run less(1), pressing 'o' runs the open script
```

**Comment by lecram** [comment]
I have implemented the 'o' command to open files using $ROVER_OPEN. The example usage above is now included in the new FAQ which was added in the last release.
