### ISSUE TITLE
Rover freezes during file transfer 

### ISSUE THREAD

**Issue by oimaasi** [lecram/rover#32]
When transfering large amount of files, I can not move around in rover, neither switching tabs nor navigating in the current directory.
The "copying xx%" status bar at the bottom is progressing, and the computer is not frozen. When the transfer is finished, rover comes back to normal life again. 
I'm wondering if that's how it supposed to be working at the moment, or is it actually a bug?

**Comment by lecram** [comment]
Yes, that's how it's supposed to work at the moment. It's not impossible to make it do the copy/move/delete in the background, but that would add some complexity. I don't plan to make any significant change to Rover in the near future, because it solves my problems and is already bigger than was intended.
