### ISSUE TITLE
m-C key sequence empties the marked files

### ISSUE THREAD

**Issue by GSI** [lecram/rover#37]
Hey what's up? Yours is still the best file manager out there.

In all those years I was very careful to not hit `m` followed by `C`, but it did happen a couple of times and once I didn't have a backup. (For a split second I had thought `C` created a new directory to where I would then move the files I just marked.)

The key sequence marks a file and then writes an empty file of the same name over it. There might be other sequences that pose the same risk.

Would you mind adding a protection against this?

**Comment by lecram** [comment]
Hi @GSI. Thanks for your feedback!
This bug was supposed to be fixed by ed9e82416fd9970147be9b8d8c8a5e1170b55f95. Unfortunately and regrettably I haven't made a new release since that change, so the bug is still present in the last released version of Rover (1.0.0).
Can you test with the latest version from git?

**Comment by GSI** [comment]
Looks good in a quick test repeating said scenario!

**Comment by lecram** [comment]
Just released version 1.0.1, including this fix. Better late than never.
