### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [lecram/rover#5]
The functions "[endwin](http://pubs.opengroup.org/onlinepubs/007908775/xcurses/endwin.html "Suspend a Curses session")" and "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process")" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[handle_segv](https://github.com/lecram/rover/blob/9fa8b0aa5acbe5a67f362b4ef495c9ad5bffbe39/rover.c#L204 "Update candidate")".

**Comment by lecram** [comment]
`handle_segv()` is only an attempt to exit more cleanly when (if) Rover crashes due to memory errors (haven't seem this happening in a while). `endwin()` restores your terminal state so that you can see the cursor, etc. If it works, OK, if it doesn't, we're already crashing anyway. I should probably replace `exit()` with `_exit()`, though.

A more serious problem is `handle_winch()`, which is called whenever the terminal is resized, allowing Rover to adjust its size accordingly. The solution suggested in your link is to replace the entire handler by a single flag assignment and constantly check for this flag in the main loop. However, Rover's main loop is blocked on user input most of the time, which means it wouldn't be able to adjust the screen immediately. In order to make this approach work correctly, we'd need to implement asynchronous user input. I'll see if this is feasible when I have some time. For now I'm leaving this issue open for suggestions.

Also note that both handlers are working correctly for me (on Linux both with glibc and musl-libc), despite this unconformity in the current implementation. **If anyone is having trouble while trying to resize Rover, please let me know.**

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")


Would you generally like to avoid that your software will eventually stumble on a deadlock because of [a questionable signal handling implementation](https://github.com/lecram/rover/blob/9fa8b0aa5acbe5a67f362b4ef495c9ad5bffbe39/rover.c#L214 "Update candidate: handle_winch")?

**Comment by lecram** [comment]
Unfortunately your suggestions seem to involve things like async input (i.e. significant refactoring), doing I/O inside the handler (causing the same problem it tries to solve?) and inline assembly (breaking portability). I'll see if I can come up with a solution, but so far this doesn't seem trivial nor critical.

Would you like to provide an unquestionable implementation via pull request? :-)

**Comment by elfring** [comment]
Are you willing to dedicate another thread for receiving of notifications by the function "[sigwaitinfo](http://stackoverflow.com/questions/6223191/dealing-with-asynchronous-signals-in-multi-threaded-program "Dealing with asynchronous signals in multi-threaded program")" or "[select](http://evbergen.home.xs4all.nl/unix-signals.html "Avoiding races with Unix signals and select() ")"?

Does the technique "multi-threading" make sense also for your user interface?

**Comment by lecram** [comment]
Fixed in @4167d62b8f987c4ca550981e3aa66d65dcb6542e.

**Comment by elfring** [comment]
Thanks for [your small source improvement](https://github.com/lecram/rover/commit/4167d62b8f987c4ca550981e3aa66d65dcb6542e "Adjusted signal handling").
